---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
  labels:
    app: backend
  name: backend
  namespace: gitops-demo
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: docker.io/benmarsden/gol-backend-prod:0187553
        ports:
        - name: backend
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
  namespace: gitops-demo
spec:
  selector:
    app: backend
  ports:
  - name: backend
    port: 3000
    targetPort: 3000
